apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  # PetClinic namespaces.
  - petclinic-cicd
  - petclinic-dev
  - petclinic-test
  - petclinic-prod
  #- ../../base/stackrox-cicd-token-generator

patches:
- target:
    kind: PipelineRun
    name: stackrox-token-secret-patchme
  patch: |-
    - op: add
      path: /spec/params/-
      value:
        name: "NAMESPACE"
        value: "petclinic-cicd"
    - op: replace
      path: /metadata/name
      value: 'stackrox-token-secret-petclinic-cicd'
