kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-gitops

bases:
  - ../../../03-cluster-services/01-sealed-secrets
  - ../../../03-cluster-services/02-openshift-pipelines
  - ../../../03-cluster-services/03-web-terminal
  - ../../../03-cluster-services/04-amq-streams
  #- ../../../03-cluster-services/05-single-sign-on
  - ../../../03-cluster-services/06-monitoring

resources:
  - cluster-services-project.yaml
