kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "12"
  labels:
    gitops.ownedBy: openshift-gitops
  name: developer-argocd-tenant
spec:
  destination:
    namespace: developer-argocd
    server: https://kubernetes.default.svc
  project: tenants
  source:
    path: tenants/developer-argocd
    repoURL: https://github.com/pittar-gitops/gitops-mono-repo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy8
        